services:
  node1:
    build: .
    container_name: nodejs-queue-node1
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      servidor: node1
    command: npm run dev
    networks:
      - app-network

  node2:
    build: .
    container_name: nodejs-queue-node2
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      servidor: node2
    command: npm run dev
    networks:
      - app-network

  nginx:
    build:
      dockerfile: dockerfile
      context: ./nginx
    container_name: nodejs-queue-nginx
    ports:
      - "80:80"
    volumes:
      - .:/usr/nginx
    networks:
      - app-network
    depends_on:
      node1:
        condition: service_completed_successfully
      node2:
        condition: service_completed_successfully

networks:
  app-network:
    driver: bridge
